---
- name: Install Software
  hosts: localhost
  become: false
  tasks:
    - name: Discover Homebrew prefix
      command: brew --prefix
      register: brew_prefix
      changed_when: false

    - name: Cleanup Homebrew
      command: brew cleanup
    - name: Update all Homebrew packages
      command: brew update
    - name: Upgrade all Homebrew packages
      command: brew upgrade
    - name: Install Software Applications
      loop:
        - firefox
        - vlc
        - libreoffice
        - grammarly-desktop
        - hyper
        - google-drive
        - telegram
        - tor-browser
        - whatsapp
        - keepassxc
        - parsec
        - microsoft-remote-desktop
        - pycharm-ce
        - android-studio
        - lens
        - zoom
        - ledger-live
        - trezor-suite
        - logi-options-plus
      vars:
        app_name: "{{ item }}"
      command: "brew install --force --cask {{ app_name }}"
      args:
        creates: "{{ brew_prefix.stdout }}/Caskroom/{{ app_name }}"

    - name: Install non cask Software Applications
      loop:
        - fish
        - kubernetes-cli
        - mas
        - rsync
        - progress
      vars:
        app_name: "{{ item }}"
      command: "brew install --force {{ app_name }}"
      args:
        creates: "{{ brew_prefix.stdout }}/Cellar/{{ app_name }}"

    - name: Install Oh My Zsh (unattended)
      shell: |
        RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"